version: "3.3"

services:
  dev-py:
    build:
      context: .
      dockerfile: ./py/Dockerfile
    volumes:
      - .:/app
    working_dir: /app

  dev-go:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    # image: tinygo/tinygo:0.30.0
    # volumes:
    #   - .:/app
    # network_mode: host
    # working_dir: /app
    # command: /bin/bash
